apiVersion: v1
kind: Service
metadata:
  name: {{ include "moaw-search.fullname" . }}-search-ui
  labels:
    {{- include "moaw-search.labels" . | nindent 4 }}
    app.kubernetes.io/component: search-ui
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "moaw-search.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: search-ui
