apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "moaw-search.fullname" . }}-search-api
  labels:
    {{- include "moaw-search.labels" . | nindent 4 }}
stringData:
  openaiKey: {{ .Values.secrets.openaiKey | required "A value for .Values.secrets.openaiKey is required" }}
