image:
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

replicaCount: 2
nameOverride: ""
fullnameOverride: ""

# Requires to be binded with an Azure AD identity
# See: https://learn.microsoft.com/en-us/azure/aks/workload-identity-deploy-cluster
serviceAccountName: moaw-search-sa

ingress:
  host: moaw-search.shopping-cart-devops-demo.lesne.pro
  tls: {}

resources:
  requests:
    cpu: .25
    memory: 256Mi
  limits:
    cpu: .5
    memory: 512Mi

api:
  acs:
    base: https://moaw-search-modr.cognitiveservices.azure.com
    token: 9abbbdb07fb4448cb059e00be1d5d0e6
  logging:
    app: DEBUG
    sys: WARN
  oai:
    base: https://moaw-search.openai.azure.com
    ada_deploy_id: text-embedding-ada-002
    gpt_deploy_id: gpt-35-turbo

redis:
  auth:
    enabled: false
  replica:
    replicaCount: 0
  resources:
    requests:
      cpu: .25
      memory: 256Mi
    limits:
      cpu: .5
      memory: 512Mi

qdrant:
  replicaCount: 2
  updateConfigurationOnChange: true
  persistence:
    size: 10Gi
    storageClassName: managed-csi
  resources:
    requests:
      cpu: .25
      memory: 256Mi
    limits:
      cpu: .5
      memory: 512Mi
