image:
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

replicaCount: 2
nameOverride: ""
fullnameOverride: ""

ingress:
  host: moaw-search.shopping-cart-devops-demo.lesne.pro
  tls: {}

secrets:
  openaiKey: ""

resources:
  requests:
    cpu: .25
    memory: 256Mi
  limits:
    cpu: .5
    memory: 512Mi

redis:
  auth:
    enabled: false
  replica:
    replicaCount: 0
  resources:
    requests:
      cpu: .25
      memory: 256Mi
    limits:
      cpu: .5
      memory: 512Mi

qdrant:
  replicaCount: 2
  updateConfigurationOnChange: true
  persistence:
    size: 10Gi
    storageClassName: managed-csi
  resources:
    requests:
      cpu: .25
      memory: 256Mi
    limits:
      cpu: .5
      memory: 512Mi
